service: harmony-client

plugins:
  - serverless-finch

custom:
  client:
    bucketName: ${self:service}-${opt:stage, self:provider.stage}-static-resources
    distributionFolder: ../client/build
    indexDocument: index.html
    errorDocument: index.html
  babelOptions:
      presets: ["es2015"]

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
