service: harmony-documentation-site

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: harmony-client # required
      localDir: _site # required

      acl: public-read # optional
      followSymlinks: true # optional
      defaultContentType: text/html # optional
      params: # optional
        - index.html:
            CacheControl: 'no-cache'
        - "*.js":
            CacheControl: 'public, max-age=31536000'

# resources:
#   Resources:
#     ResBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: harmony-client
#         AccessControl: PublicRead
#         WebsiteConfiguration:
#           IndexDocument: index.html
#           ErrorDocument: error.html
