version: 0.2

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install zip
      - npm install -g serverless
      - npm install -g serverless-offline
      - npm install -g serverless-finch
  build:
    commands:
      # Pull the deployment configuration file
      - cd deployment-config
      - npm install
      - node node_modules/babel-cli/bin/babel-node.js pull-deployment-configuration.js > deployment-config.json
      - cat deployment-config.json
      - cd ..

      # Build graphql-service
      - cd graphql-service
      - npm install
      - sls package
      - cd ..

      # Build client
      - cd client
      - npm install
      - npm run build
      - cd ..
  post_build:
    commands:
      # Deploy graphql-service
      - cd graphql-service
      - sls deploy --package .serverless
      - cd ..

      # Deploy client
      - cd client
      - sls client deploy --no-confirm
