version: 0.1

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install zip
      - npm install -g serverless
      - npm install -S serverless-finch
      - npm install -S serverless-offline
      - npm install -S babel-cli
      - npm install -S babel-preset-es2015
      - npm install aws-sdk
      - node node_modules/babel-cli/bin/babel-node.js deployment-configuration/pull-deployment-configuration.js > deployment-configuration.json
      - cat deployment-configuration.json
  build:
    commands:
  post_build:
    commands:
      - sls deploy
      # - sls client deploy
artifacts:
  files:
    - serverless.yml
    - publish.zip
  discard-paths: yes
